### ISSUE TITLE
H264 Payload index out of range

### ISSUE THREAD

**Issue by tskinn** [pion/rtp#27]
### Your environment.
  - Version: v1.1.4
  - Browser: Chrome 79.0.3945.79
  - Error:

```
panic: runtime error: index out of range [0] with length 0
goroutine 11 [running]:
github.com/pion/rtp/codecs.(*H264Payloader).Payload.func1(0x66bb4008, 0x0, 0xfd1f8)
        GOPATH/pkg/mod/github.com/pion/rtp@v1.1.4/codecs/h264_packet.go:54 +0x3b0
github.com/pion/rtp/codecs.emitNalus(0x66bb4000, 0xfd200, 0xfd200, 0xc206d0)
        GOPATH/pkg/mod/github.com/pion/rtp@v1.1.4/codecs/h264_packet.go:36 +0x104
github.com/pion/rtp/codecs.(*H264Payloader).Payload(0x5419b4, 0x4a4, 0x66bb4000, 0xfd200, 0xfd200, 0x0, 0x0, 0x0)
        GOPATH/pkg/mod/github.com/pion/rtp@v1.1.4/codecs/h264_packet.go:53 +0x7c
github.com/pion/rtp.(*packetizer).Packetize(0xc44b70, 0x66bb4000, 0xfd200, 0xfd200, 0x0, 0x0, 0xfd200, 0xfd200)
        GOPATH/pkg/mod/github.com/pion/rtp@v1.1.4/packetizer.go:75 +0x54
github.com/pion/webrtc/v2.(*Track).WriteSample(0xc7c4e0, 0x66bb4000, 0xfd200, 0xfd200, 0x0, 0x0, 0x0)
        GOPATH/pkg/mod/github.com/pion/webrtc/v2@v2.1.15/track.go:126 +0x48
main.main.func1(0xc0b5e0, 0xc0f580, 0xc7c4e0)
        SRCDIR/play.go:105 +0x1c4
created by main.main
        SRCDIR/play.go:74 +0x4dc
```

### What did you do?

Most of the code below is copied from the play-from-disk example in the pio/webrtc repo and some internal helper functions used by the examples.

<details><summary>Code</summary>

```go
package main

import (
	"bufio"
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"math/rand"
	"os"
	"strings"

	"github.com/blackjack/webcam"
	"github.com/pion/webrtc/v2"
	"github.com/pion/webrtc/v2/pkg/media"
)

var compress = false

func main() {
	cam, err := webcam.Open("/dev/video0")
	if err != nil {
		panic(err.Error())
	}
	defer cam.Close()

	if _, _, _, err = cam.SetImageFormat(webcam.PixelFormat(34363248), uint32(960), uint32(720)); err != nil {
		panic(err)
	}

	// Wait for the offer to be pasted
	offer := webrtc.SessionDescription{}
	Decode(MustReadStdin(), &offer)

	// We make our own mediaEngine so we can place the sender's codecs in it.  This because we must use the
	// dynamic media type from the sender in our answer. This is not required if we are the offerer
	mediaEngine := webrtc.MediaEngine{}
	err = mediaEngine.PopulateFromSDP(offer)
	if err != nil {
		panic(err)
	}

	// Search for VP8 Payload type. If the offer doesn't support VP8 exit since
	// since they won't be able to decode anything we send them
	var payloadType uint8

	payloadType = webrtc.DefaultPayloadTypeH264

	// Create a new RTCPeerConnection
	api := webrtc.NewAPI(webrtc.WithMediaEngine(mediaEngine))
	peerConnection, err := api.NewPeerConnection(webrtc.Configuration{
		ICEServers: []webrtc.ICEServer{
			{
				URLs: []string{"stun:stun.l.google.com:19302"},
			},
		},
	})
	if err != nil {
		panic(err)
	}

	// Create a video track
	videoTrack, err := peerConnection.NewTrack(payloadType, rand.Uint32(), "video", "pion")
	if err != nil {
		panic(err)
	}
	if _, err = peerConnection.AddTrack(videoTrack); err != nil {
		panic(err)
	}

	go func() {
		timeout := uint32(5) //5 seconds

		err = cam.StartStreaming()
		if err != nil {
			fmt.Println(err)
			return
		}

		// Send our video file frame at a time. Pace our sending so we send it at the same speed it should be played back as.
		// This isn't required since the video is timestamped, but we will such much higher loss if we send all at once.
		//sleepTime := time.Millisecond * time.Duration((float32(header.TimebaseNumerator)/float32(header.TimebaseDenominator))*1000)
		for {
			err = cam.WaitForFrame(timeout)
			if err != nil {
				panic(err)
			}

			switch err.(type) {
			case nil:
			case *webcam.Timeout:
				fmt.Println(err)
				continue
			default:
				panic(err)
			}

			frame, err := cam.ReadFrame()
			if err != nil {
				panic(err)
			}
			fmt.Fprintln(os.Stderr, string(frame))
			err = videoTrack.WriteSample(media.Sample{Data: frame})
			if err != nil {
				fmt.Println(err)
			}
		}
	}()

	// Set the handler for ICE connection state
	// This will notify you when the peer has connected/disconnected
	peerConnection.OnICEConnectionStateChange(func(connectionState webrtc.ICEConnectionState) {
		fmt.Printf("Connection State has changed %s \n", connectionState.String())
	})

	// Set the remote SessionDescription
	if err = peerConnection.SetRemoteDescription(offer); err != nil {
		fmt.Println("set session description")
		panic(err)
	}

	// Create answer
	answer, err := peerConnection.CreateAnswer(nil)
	if err != nil {
		fmt.Println("create answer")
		panic(err)
	}

	// Sets the LocalDescription, and starts our UDP listeners
	if err = peerConnection.SetLocalDescription(answer); err != nil {
		fmt.Println("set local descriptoin")
		panic(err)
	}

	// Output the answer in base64 so we can paste it in browser
	fmt.Println(Encode(answer))

	// Block forever
	select {}
}

// MustReadStdin blocks until input is received from stdin
func MustReadStdin() string {
	r := bufio.NewReader(os.Stdin)

	var in string
	for {
		var err error
		in, err = r.ReadString('\n')
		if err != io.EOF {
			if err != nil {
				panic(err)
			}
		}
		in = strings.TrimSpace(in)
		if len(in) > 0 {
			break
		}
	}

	fmt.Println("")

	return in
}

// Encode encodes the input in base64
// It can optionally zip the input before encoding
func Encode(obj interface{}) string {
	b, err := json.Marshal(obj)
	if err != nil {
		panic(err)
	}

	if compress {
		b = zip(b)
	}

	return base64.StdEncoding.EncodeToString(b)
}

func zip(in []byte) []byte {
	var b bytes.Buffer
	gz := gzip.NewWriter(&b)
	_, err := gz.Write(in)
	if err != nil {
		panic(err)
	}
	err = gz.Flush()
	if err != nil {
		panic(err)
	}
	err = gz.Close()
	if err != nil {
		panic(err)
	}
	return b.Bytes()
}

// Decode decodes the input from base64
// It can optionally unzip the input after decoding
func Decode(in string, obj interface{}) {
	b, err := base64.StdEncoding.DecodeString(in)
	if err != nil {
		panic(err)
	}

	if compress {
		b = unzip(b)
	}

	err = json.Unmarshal(b, obj)
	if err != nil {
		panic(err)
	}
}

func unzip(in []byte) []byte {
	var b bytes.Buffer
	_, err := b.Write(in)
	if err != nil {
		panic(err)
	}
	r, err := gzip.NewReader(&b)
	if err != nil {
		panic(err)
	}
	res, err := ioutil.ReadAll(r)
	if err != nil {
		panic(err)
	}
	return res
}
```

</details>

### What did you expect?

I'm attempting to run pion on a raspberry pi and stream the camera feed. It's very likely that I am handling the H264 frames incorrectly as I am a noob but even then I did not expect to see this invalid index panic from the rtp package.

### What happened?

Panic index out of range. See error above.

**Comment by lxb531** [comment]
add following code to avoid empty slice
emitNalus(payload, func(nalu []byte) {
```
		if len(nalu) == 0 {
			return
		}
```

**Comment by Sean-Der** [comment]
Hey @lxb531 would you mind making a PR, would love to merge it right away!

thanks
